#!/bin/bash

#
# Back2NTFS - v0.9
#   by Andy Forceno <andy@aurorabox.tech>
#
# Tar /home/user and /etc on many remote hosts
# Copy to an NTFS NAS device & create and verify SHA1 checksums
# To be run bi-weekly via cron
#

# Hosts to be backed up via SSH (passwordless login required for automation)
source ~/scripts/bin/hosts_check

# Location to log to on each host specified in hosts_check
log="~/backup-$(date +%m%d%y).log"
# Path to backup dir
backup_path="/media/andy/external/Backups"

echo -e "Back2NTFS: ***** Begin back2ntfs.sh *****\n"
echo -e "Back2NTFS: See "$log" on each host for individual backup logs"

for i in "${HOSTS[@]}"; do
  echo "Connecting to: $i"
  # Pass $vars to remote host
  ssh "$i" LC_i="$i" LC_log="$log" LC_backup_path="$backup_path" bash << 'EOF' 
  if [[ ! -f "$LC_log" ]]; then
    touch "$LC_log"
  fi

  # Backup /home/andy
  echo -e "Back2NTFS: $LC_i: Creating tar file of /home/andy in "$LC_backup_path"/"$LC_i"...\n" >> "$LC_log"
  sudo touch "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar >> "$LC_log"
  # Exclude caches, and most folders that begin with a dot
  tar -X /home/andy/scripts/.excludes --exclude-caches-all -cvPf "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar /home/andy >> "$LC_log" && wait
  sha1sum "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar > "$LC_backup_path"/"$LC_i"/home-$(date +%m%d%y).tar.sha1 >> "$LC_log" && wait

  # Backup /etc
  echo -e "Back2NTFS: $LC_i: Creating tar file of /etc in "$LC_backup_path"/"$LC_i"...\n" >> "$LC_log"
  sudo touch "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar >> "$LC_log"
  sudo tar --exclude-caches-all -cvPf "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar /etc >> "$LC_log" && wait
  sha1sum "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar > "$LC_backup_path"/"$LC_i"/etc-$(date +%m%d%y).tar.sha1 >> "$LC_log" && wait
EOF

  # Location of backups on host executing back2ntfs 
  # In my case this is different than the location on remote hosts
  cd /media/external/Backups/"$i"/
  # Find and delete .tar and .sha1 files older than 1 month (works for February too!)
  echo "Back2NTFS: Deleting old backups..."
  find . -type f \( -iname \*.tar -o -iname \*.sha1 \) -mtime +28 -exec rm -i -f {} \+ 

  ## Verify .sha1 checksums before exiting
  for j in $(find . -name '*.sha1'); do
    checksum=$(sha1sum -c "$j" | head -n 1 | awk -F": " '{ print $2 }')
    echo "Back2NTFS: Verifying checksum of tar backup $(echo "$j" | sed 's/.sha1//g')..."
    if [[ "$checksum" = "FAILED" ]]; then
      echo "Back2NTFS: $(echo "$j" | sed 's/.sha1//g'): Bad checksum!" 
      /home/andy/scripts/shuttle -p -n all "$i: Bad checksum!" "$j failed checksum verification at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
    else
      echo "Back2NTFS: $(echo "$j" | sed 's/.sha1//g'): OK!"
    fi
  done
done

echo -e "Back2NTFS: ***** End back2ntfs.sh ***** Goodbye!\n"

