#! /bin/bash

# hostname-isup - Check if a host is up
# 	by Andy Forceno <andy@aurorabox.tech>
#

# This script could easily be expanded to include multiple hosts
# You can borrow code from the hosts_check and spaced or smartmon scripts  :-)

if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
else
	echo "SHuttle-utils: Error: No config file found!"
	exit 1
fi

# TODO: Move user-defined vars to shuttle-utils.conf
# Host IP address and name
host_addr="192.168.1.2"

# How often to ping host
sleep_time="2m"

while true; do
	ping -w 10 -c 3 "$host_addr" > /dev/null
	rc=$?

	# If exit code != 0, ping failed so host is (probably) down!
	if [[ $rc -ne 0 ]]; then                  
		shuttle -p -n "$device" "$HOSTNAME is down or not responding to pings (rc = $rc)" > /dev/null
	fi
	
	sleep $sleep_time
done
