#! /bin/bash

# ipnotif: IP Address Change Push Notifier
# by Andy Forceno <andy@aurorabox.tech>
#

# Uses the IPify API to obtain external IP
# And compares it to the previously obtained address
# Requires curl

# This script is brought to you by the music of Natasha Kmeto: https://soundcloud.com/natashakmeto

if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
else
	echo "SHuttle-utils: Error: No config file found!"
	exit 1
fi

# API call to obtain IP address
# See: https://www.ipify.org/
new_ip=$(curl -s 'https://api.ipify.org?format=text')

# Last known IP
if [ -e "$conf_path/.iphistory" ]; then
	last_ip=$(tac "$conf_path"/.iphistory | grep -m 1 '.' | awk '{print $4}')
	if [[ "$last_ip" != "$new_ip" ]]; then
		$shuttle_path/shuttle -p -n "$device" "$HOSTNAME: External IP address change" "Current IP: $new_ip"
	fi
# Write date & address to file for IP address history
else 
	touch "$conf_path/.iphistory" 
fi	
echo "$(date "+%D %H:%M") - $new_ip" >> $conf_path/.iphistory
fi


