#! /bin/bash

transmission=$(ps x | grep [t]ransmission-gtk)

if [ -z "$transmission" ]; then
echo "seed_check: Transmission-gtk is not running! Executing..."
	transmission-gtk &
echo "seed_check: Done!"
fi

exit 0
