#! /bin/bash

# smartmon_long - Long S.M.A.R.T. Test Results Push Notifier 
# 	by Andy Forceno <andy@aurorabox.tech>
#
# Runs the long S.M.A.R.T. test for disks on remote hosts and pushes & mails results

# It is recommended to run this weekly
# You will need passwordless-sudo on the remote devices to automate this script

# TODO: Full SMART test results aren't being pushed. API seems to interpret something in the smartctl output incorrectly

if [ -e "$HOME"/.config/shuttle-utils/shuttle-utils.conf ]; then
	source "$HOME"/.config/shuttle-utils/shuttle-utils.conf
else
	echo "SHuttle-utils: Error: No config file found!"
	exit 1
fi

# Check if hosts are available before running remote SMART tests
source "$bin_path"/hosts_check

# TODO: Add for j in DRIVES array loop 
# Iterate through hosts list
for i in "${HOSTS[@]}"; do
	echo "Smartmon_long: Connecting to: $i"
	# Pass locally-declared vars to remote host
	ssh "$i" LC_i="$i" LC_drive="$drive" LC_device="$device" LC_mailto="$mailto" LC_shuttle_path="$shuttle_path" bash << 'EOF' 
	echo -e "smartmon_long: Begin SMART long test for host: $LC_i"
   	sudo smartctl -t long "$LC_drive" 2>/dev/null && wait $!
    long_results=$(sudo smartctl -l selftest "$LC_drive" 2>/dev/null)
  # echo -e "smartmon_long: self-test results for $LC_i: $long_results"
  # echo -e "$(date +%R) on $(date +%m-%d-%y):\n $long_results" | mail -s "$LC_i: SMART long test for $LC_drive" "$LC_mailto"
    "$LC_shuttle_path"/shuttle -p -n "$LC_device" "$LC_i: SMART Long Test" "$LC_DRIVES: $long_results at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
EOF
done
