#! /bin/bash

# smartmon_long - Long S.M.A.R.T. Test Results Push Notifier - v1.0
# 	by Andy Forceno <andy@aurorabox.tech>
#
# Runs the long S.M.A.R.T. test for disks on remote hosts and pushes & mails results

# It is recommended to run this weekly
# You will need passwordless-sudo on the remote devices to automate this script

# Device to send push notifications to
device="phone"

# Drive to scan on remote host
# TODO: Create an array so we can do multiples drives on each host
drive="/dev/sda"

# User to send mail to on remote host
mailto="root@$(hostname)"

# Check if hosts are available before running remote SMART tests
source hosts_check

# Iterate through hosts list
for j in "${HOSTS[@]}"; do
	echo -e "Smartmon-long: Begin SMART long test for host: $j"
        long_test=$(ssh "$j" "sudo smartctl -t long $drive")
        long_result=$(sudo smartctl -l selftest "$drive")
	echo -e "Smartmon_long: Result for $j: $long_result"
# Always notify of long test results
        echo -e "$(date +%R) on $(date +%m-%d-%y):\n$long_result" | mail -s "$j: SMART long test for $drive" "$mailto"
      	shuttle -p -n "$device" "$host: SMART Long Test" "$drive "$long_result" at $(echo "$(date +%R) on $(date +%m-%d-%y)")"
done
