#! /bin/bash

# spaced - Disk Space Notification Daemon - v1.0
# 	By Andy Forceno <andy@aurorabox.tech>
#

# Location of local disk copy of repo
BASEDIR="$HOME/scripts/bin"

MAILTO="root@aurorabox"

# Check if hosts are available before checking disc space
source "$BASEDIR"/hosts_check

# Percentage threshold at which to warn user of low disk space
percent="98"
# Everything after the ssh command will be executed on each remote host
# Mail will be sent to root at each remote host
for i in "${HOSTS[@]}"; do
	echo "Spaced: Checking disk space on $i..."
# Pass $i to remote host
	ssh "$i" LC_i="$i" LC_percent="$percent" LC_mailto="$MAILTO" bash << 'EOF' 
# List of all block devices
	df_output=$(df -lh | grep "/dev/sd.*")
# Devices
	dev_files=$(echo -e "$df_output" | awk '{ print $1 }')
# Mountpoints
	mounts=($(echo -e "$df_output" | awk '{ print $6 }'))
# Percent free space
	free_space=($(echo -e "$df_output" | awk '{ print $5 }' | tr -d '%'))

# For each line in $free_space, if $j < some %, warn!!
	for j in "${free_space[@]}"; do
		if [[ "$j" > "$LC_percent" ]]; then
			line_num=$(echo -e "$df_output" | grep -n "$j" | cut -f1 -d:)
		# df line with drive info
			df_line=$(echo -e "$df_output" | grep -n "$j" | cut -d: -f2-)
			sudo echo "Spaced: $LC_i: $(echo -e "$mounts" | sed -n $line_num'p') partition has less than $percent% free space!" >> /var/log/cron.log
			# echo -e "$(df -lh | head -n1)\n$df_line" | mail -s "space.d: Low disk space for $(echo -e "$dev_files" | sed -n $line_num'p')" "$LC_mailto"
			/usr/bin/shuttle -p -n all "$LC_i: Low disk space for $(echo -e "$dev_files" | sed -n $line_num'p')" "$(echo -e "$mounts" | sed -n $line_num'p') partition has $((100-$(echo -e "$free_space" | sed -n $line_num'p')))% free space"
		fi
	done
EOF
done
exit 0
