#! /bin/bash
#
# syncs.sh - Sync files to machines on LAN via rsync - v2.0
# by Andy Forceno <andy@aurorabox.tech>
#
# Distributed under the MIT license:
# https://opensource.org/licenses/MIT

# I put an entry in crontab for this script: 
# */5  * * * *   user     /bin/bash /path/to/syncs.sh 2>&1 | /path/to/timestamp.sh >> /path/to/syncs.log
# This causes cron to execute syncs.sh every 5 minutes, then run it's output through a timestamping script
# And then echo the timestamped syncs.sh output to syncs.log

# timestamp.sh:
# #!/bin/bash
#while read x; do
#    echo -n "`date +%m/%d/%Y\ %H:%M:%S`";
#    echo -n " ";
#    echo $x;
#done
#

SOURCE_DIR="/home/andy"
DEST_DIR="/home/andy"

# Check if machines are available before syncing
source /home/andy/scripts/bin/hosts_check

# Do not sync file to self
HOSTS=($(echo "${HOSTS[@]}" | sed -e "s/\Aurorabox//g" -e "s/\Vivobook//g"))

for j in "${HOSTS[@]}"; do
    echo "Syncs: ---- [ "$j" ] ----"
    rsync -auhvz -e ssh "$SOURCE_DIR"/.tasks "$j":"$DEST_DIR"/.tasks # 2>&1 /dev/null
    rsync -auhvz -e ssh "$SOURCE_DIR"/.bash_aliases "$j":"$DEST_DIR"/.bash_aliases # 2>&1 /dev/null
done
